#!/bin/bash -e

TZDATA_TAR=tzdata2023c.tar.gz
TZDATA_URL=https://data.iana.org/time-zones/releases/$TZDATA_TAR
TZDATA_FILE=zone1970.tab
RES_FILE=src/Objects/RegionStore.vala

WORKDIR=$(mktemp -d)

wget $TZDATA_URL -O $WORKDIR/$TZDATA_TAR
tar xvf $WORKDIR/$TZDATA_TAR -C $WORKDIR

TZDATA=$(cat $WORKDIR/$TZDATA_FILE | grep -v "#" | awk '{ print $3 }' | sort -u)

cat << EOF > $RES_FILE
/* Automatically generated by generate_zone.sh, do not edit */

namespace Hourglass.Objects.RegionStore {
    public static void init_store (GLib.ListStore regions) {
EOF

for tz in $TZDATA; do
    echo "        regions.append (new Region (\"$tz\", _(\"$tz\")));" >> $RES_FILE
done

cat << EOF >> $RES_FILE
    }
}
EOF

rm -r $WORKDIR
