name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  gettext:
    name: Gettext
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gettext
        uses: ryonakano/actions/gettext-template@horus
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          regenerate_po: 'true'
